<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Map Output</name>
  <uuid>d5e0d6c8-0b25-4d44-af49-6c10bd70a56e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Predictive Model Result where
		the prediction is the prediction of 'ML model invocation' , 
		the probability is the maximum probability of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
